use std::io::Error;

fn main() -> Result<(), Error> {
    println!("Cleanup resources from current graph ...");
    Ok(())
}
